# The following are a list of mappings that assist with the project scripts, used to enforce the same naming conventions for teams

team_mapping = {
    'Dallas Cowboys': 'DAL',
    'San Francisco 49ers': 'SF',
    'Buffalo Bills': 'BUF',
    'Philadelphia Eagles': 'PHI',
    'Detroit Lions': 'DET',
    'Miami Dolphins': 'MIA',
    'Baltimore Ravens': 'BAL',
    'Los Angeles Rams': 'LAR',
    'St. Louis Rams': 'LAR',
    'Kansas City Chiefs': 'KC',
    'Minnesota Vikings': 'MIN',
    'Green Bay Packers': 'GB',
    'New Orleans Saints': 'NO',
    'Jacksonville Jaguars': 'JAX',
    'Arizona Cardinals': 'ARI',
    'Cincinnati Bengals': 'CIN',
    'Houston Texans': 'HOU',
    'Atlanta Falcons': 'ATL',
    'Cleveland Browns': 'CLE',
    'Indianapolis Colts': 'IND',
    'Chicago Bears': 'CHI',
    'Washington Commanders': 'WAS',
    'Washington Football Team': 'WAS',
    'Washington Redskins': 'WAS',
    'Los Angeles Chargers': 'LAC',
    'San Diego Chargers': 'LAC',
    'Seattle Seahawks': 'SEA',
    'Denver Broncos': 'DEN',
    'Tampa Bay Buccaneers': 'TB',
    'Tennessee Titans': 'TEN',
    'Carolina Panthers': 'CAR',
    'Las Vegas Raiders': 'LV',
    'Oakland Raiders': 'LV',
    'Pittsburgh Steelers': 'PIT',
    'New York Giants': 'NYG',
    'New England Patriots': 'NE',
    'New York Jets': 'NYJ'
}

team_name_mapping = {
    'Cowboys': 'DAL',
    '49ers': 'SF',
    'Bills': 'BUF',
    'Eagles': 'PHI',
    'Lions': 'DET',
    'Dolphins': 'MIA',
    'Ravens': 'BAL',
    'Rams': 'LAR',
    'Chiefs': 'KC',
    'Vikings': 'MIN',
    'Packers': 'GB',
    'Saints': 'NO',
    'Jaguars': 'JAX',
    'Cardinals': 'ARI',
    'Bengals': 'CIN',
    'Texans': 'HOU',
    'Falcons': 'ATL',
    'Browns': 'CLE',
    'Colts': 'IND',
    'Bears': 'CHI',
    'Commanders': 'WAS',
    'Chargers': 'LAC',
    'Seahawks': 'SEA',
    'Broncos': 'DEN',
    'Buccaneers': 'TB',
    'Titans': 'TEN',
    'Panthers': 'CAR',
    'Raiders': 'LV',
    'Steelers': 'PIT',
    'Giants': 'NYG',
    'Patriots': 'NE',
    'Jets': 'NYJ'
}

position_mapping = {
    'LS': 'DST',  
    'DT': 'DST',  
    'C': 'C',      
    'LB': 'DST',   
    'CB': 'DST',   
    'P': 'DST',    
    'T': 'T',      
    'DE': 'DST',   
    'QB': 'QB',    
    'WR': 'WR',    
    'unknown': 'unknown',  
    'K': 'K',      
    'TE': 'TE',    
    'G': 'T',      
    'FB': 'RB',    
    'RB': 'RB',    
    'S': 'DST'     
}

team_encoding = {
    'DAL': 0,
    'SF': 1,
    'BUF': 2,
    'PHI': 3,
    'DET': 4,
    'MIA': 5,
    'BAL': 6,
    'LAR': 7,
    'STL': 7,
    'KC': 8,
    'MIN': 9,
    'GB': 10,
    'NO': 11,
    'JAX': 12,
    'ARI': 13,
    'CIN': 14,
    'HOU': 15,
    'ATL': 16,
    'CLE': 17,
    'IND': 18,
    'CHI': 19,
    'WAS': 20,
    'LAC': 21,
    'SD': 21,
    'SEA': 22,
    'DEN': 23,
    'TB': 24,
    'TEN': 25,
    'CAR': 26,
    'LV': 27,
    'OAK': 27,
    'PIT': 28,
    'NYG': 29,
    'NE': 30,
    'NYJ': 31
}

coach_team_encoding = {
    'ARI': 'ARI',
    'ATL': 'ATL',
    'BAL': 'BAL',
    'BUF': 'BUF',
    'CAR': 'CAR',
    'CHI': 'CHI',
    'CIN': 'CIN',
    'CLE': 'CLE',
    'DAL': 'DAL',
    'DEN': 'DEN',
    'DET': 'DET',
    'GNB': 'GB',
    'HOU': 'HOU',
    'IND': 'IND',
    'JAX': 'JAX',
    'KAN': 'KC',
    'LAC': 'LAC',
    'SDG': 'LAC',
    'LAR': 'LAR',
    'STL': 'LAR',
    'LVR': 'LV',
    'OAK': 'LV',
    'MIA': 'MIA',
    'MIN': 'MIN',
    'NOR': 'NO',
    'NWE': 'NE',
    'NYG': 'NYG',
    'NYJ': 'NYJ',
    'PHI': 'PHI',
    'PIT': 'PIT',
    'SEA': 'SEA',
    'SFO': 'SF',
    'TAM': 'TB',
    'TEN': 'TEN',
    'WAS': 'WAS'
}

position_encoding = {
    'QB': 1,
    'RB': 2,
    'WR': 3,
    'TE': 4,
    'K': 5,
    'DST': 6
}
